### ISSUE TITLE
Build Failure due to lack of -lm

### ISSUE THREAD

**Issue by SolarAquarion** [finalterm/finalterm#6]
c  -o src/finalterm 'src/src@@finalterm@exe/meson-generated_.._.._data_resources.c.o' 'src/src@@finalterm@exe/meson-generated_Autocompletion.c.o' 'src/src@@finalterm@exe/meson-generated_CharacterAttributes.c.o' 'src/src@@finalterm@exe/meson-generated_ColorScheme.c.o' 'src/src@@finalterm@exe/meson-generated_Command.c.o' 'src/src@@finalterm@exe/meson-generated_Encoder.c.o' 'src/src@@finalterm@exe/meson-generated_FinalTerm.c.o' 'src/src@@finalterm@exe/meson-generated_KeyBindings.c.o' 'src/src@@finalterm@exe/meson-generated_Metrics.c.o' 'src/src@@finalterm@exe/meson-generated_NestingContainer.c.o' 'src/src@@finalterm@exe/meson-generated_NotifyingList.c.o' 'src/src@@finalterm@exe/meson-generated_ScrollableTreeView.c.o' 'src/src@@finalterm@exe/meson-generated_Settings.c.o' 'src/src@@finalterm@exe/meson-generated_SettingsWindow.c.o' 'src/src@@finalterm@exe/meson-generated_StatusBar.c.o' 'src/src@@finalterm@exe/meson-generated_TerminalOutput.c.o' 'src/src@@finalterm@exe/meson-generated_TerminalStream.c.o' 'src/src@@finalterm@exe/meson-generated_Terminal.c.o' 'src/src@@finalterm@exe/meson-generated_TerminalView.c.o' 'src/src@@finalterm@exe/meson-generated_TerminalWidget.c.o' 'src/src@@finalterm@exe/meson-generated_TextMenu.c.o' 'src/src@@finalterm@exe/meson-generated_TextView.c.o' 'src/src@@finalterm@exe/meson-generated_Theme.c.o' 'src/src@@finalterm@exe/meson-generated_Utilities.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -Wl,-O1 -Wl,--start-group -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -Wl,--end-group -lgee-0.8 -lgobject-2.0 -lglib-2.0 -lkeybinder-3.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lutil -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  
/bin/ld: /tmp/ccYuwacr.ltrans3.ltrans.o: undefined reference to symbol 'round@@GLIBC_2.2.5'
/usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by jtojnar** [comment]
What platform and version of libraries do you use? It works fine for me on NixOS Linux with Vala 0.38.4 or 0.40.0:

```
Version: 0.45.1
Source dir: /home/jtojnar/finalterm
Build dir: /home/jtojnar/finalterm/build
Build type: native build
Project name: finalterm
Native C compiler: gcc (gcc 7.3.0 "gcc (GCC) 7.3.0")
Native Vala compiler: valac (valac 0.38.4)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /nix/store/ms8zi9sndgcgvmm07j6v2cknjh8x249j-pkg-config-0.29.2/bin/pkg-config (0.29.2)
Native dependency gtk+-3.0 found: YES 3.22.29
Native dependency gee-0.8 found: YES 0.20.1
Native dependency keybinder-3.0 found: YES 0.3.0
Native dependency json-glib-1.0 found: YES 1.4.2
Library posix found: YES
Library linux found: YES
Library util found: YES
Configuring config.h using configuration
Program meson_post_install.py found: YES (/home/jtojnar/finalterm/meson_post_install.py)
Configuring bash_startup using configuration
Configuring finalterm.1 using configuration
Native dependency glib-2.0 found: YES 2.56.0
Program glib-compile-schemas found: YES (/nix/store/szcis3117qd65i22322fjsk3bzljc6bc-glib-2.56.0-dev/bin/glib-compile-schemas)
Build targets in project: 8
Found ninja-1.8.2 at /nix/store/4nii01w7imkq28ciij0xgqik08cvzxv0-ninja-1.8.2/bin/ninja
```

**Comment by SolarAquarion** [comment]
I'm using Arch Linux, it's not finding -libm

**Comment by jtojnar** [comment]
It looks like we do use `GLib.Math.round`

https://github.com/finalterm/finalterm/blob/c55cfda9b20a3249436d86784143244e34f56a1f/src/TerminalView.vala#L162

and [its documentation](https://valadoc.org/glib-2.0/GLib.Math.round.html) indeed calls for linking with `libm`. Why it works on my system baffles me.
